# This workflow will build a Java project with Gradle
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-gradle

name: SlimeVR Server

on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    
    - name: Clone Slime Java Commons
      uses: actions/checkout@v2.3.4
      with:
        repository: Eirenliel/slime-java-commons
        # Relative path under $GITHUB_WORKSPACE to place the repository
        path: Slime Java Commons
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2.1.0
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Test with Gradle
      run: ./gradlew clean test

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2.3.4
    
    - name: Clone Slime Java Commons
      uses: actions/checkout@v2.3.4
      with:
        repository: Eirenliel/slime-java-commons
        # Relative path under $GITHUB_WORKSPACE to place the repository
        path: Slime Java Commons
    
    - name: Set up JDK 8
      uses: actions/setup-java@v2.1.0
      with:
        java-version: '8'
        distribution: 'adopt'
        
    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
      
    - name: Build with Gradle
      run: ./gradlew clean serverJar
      
    - name: Upload the Server JAR as a Build Artifact
      uses: actions/upload-artifact@v2.2.4
      with:
        # Artifact name
        name: "SlimeVR-Server" # optional, default is artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: build/libs/*
